# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

os:
- linux
- osx

r:
- oldrel
- release
- devel
- 3.3.0
- 3.2.5

env:
- TravisCI=true

cache: packages
warnings_are_errors: true

matrix:
  exclude:
  - os: osx
    r: devel
  - os: osx
    r: oldrel

before_install:
- export TZ=UTC
- cd packages/RSuite
- rm -rf .Rprofile
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo chown -R $(whoami) /usr/local/share/man/man7; brew install libgit2; fi

addons:
  apt:
    packages:
    - libxml2-dev
    - libssl-dev
    - libcurl4-gnutls-dev
    - zlib1g-dev
    - libgit2-dev
    - libaio1

install:
- if [ "$TRAVIS_R_VERSION_STRING" == "3.2.5" ]; then export R_REPOS="'https://mran.microsoft.com/snapshot/2020-07-01/'"; else export R_REPOS="getOption('repos')"; fi
- Rscript -e "install.packages(c('devtools'), repos = ${R_REPOS});if (!all(c('devtools') %in% installed.packages())) { q(status = 1, save = 'no')}"
- Rscript -e "install.packages(c('knitr'), repos = ${R_REPOS});if (!all(c('knitr') %in% installed.packages())) { q(status = 1, save = 'no')}"
- Rscript -e "install.packages(c('rmarkdown'), repos = ${R_REPOS});if (!all(c('rmarkdown') %in% installed.packages())) { q(status = 1, save = 'no')}"
- Rscript -e "install.packages(c('testthat'), repos = ${R_REPOS});if (!all(c('testthat') %in% installed.packages())) { q(status = 1, save = 'no')}"
- Rscript -e "devtools::install_deps(deps = T, repos = ${R_REPOS})"
- Rscript -e "devtools::document()"

script:
- R CMD build .
- R CMD check *tar.gz
- Rscript -e 'devtools::install(repos = ${R_REPOS})'
- cd ../../tests
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then Rscript run_tests.R; else sudo -E env "PATH=$PATH" Rscript run_tests.R; fi

after_script:
- cat logs/*
