# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

os:
- linux
- osx

r:
- oldrel
- release
- devel
- 3.3.0
- 3.2.5

env:
- TravisCI=true

cache: packages
warnings_are_errors: true

matrix:
  exclude:
  - os: osx
    r: devel
  - os: osx
    r: oldrel

before_install:
- cd packages/RSuite
- rm -rf .Rprofile
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo chown -R $(whoami) /usr/local/share/man/man7; brew install libgit2; fi

addons:
  apt:
    packages:
    - libxml2-dev
    - libssl-dev
    - libcurl4-openssl-dev
    - zlib1g-dev
    - libgit2-dev

install:
- Rscript -e 'install.packages(c("devtools"));if (!all(c("devtools") %in% installed.packages())) { q(status = 1, save = "no")}'
- Rscript -e 'install.packages(c("knitr"));if (!all(c("knitr") %in% installed.packages())) { q(status = 1, save = "no")}'
- Rscript -e 'install.packages(c("testthat"));if (!all(c("testthat") %in% installed.packages())) { q(status = 1, save = "no")}'
- Rscript -e 'devtools::install_deps(deps = T)'
- Rscript -e 'devtools::document()'

script:
- R CMD build .
- R CMD check *tar.gz
- Rscript -e 'devtools::install()'
- cd ../../tests
- sudo -E env "PATH=$PATH" Rscript run_tests.R

after_script:
- cat logs/*
