# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
pandoc: false
cache: packages

before_install: cd packages/RSuite

install:
  - Rscript -e 'if(!"devtools" %in% rownames(installed.packages())) { install.packages("devtools", dependencies = TRUE) }'
  - Rscript -e 'if(!"covr" %in% rownames(installed.packages())) { install.packages("covr", dependencies = TRUE) }'
  - Rscript -e 'devtools::install_deps(pkg = ".", dependencies = TRUE)'
  
script:
  - R CMD build . --no-build-vignettes --no-manual
