# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary_201811

# Adapt as necessary starting from here

environment:
  USE_RTOOLS: true
  WARNINGS_ARE_ERRORS: 1

  matrix:
  - R_VERSION: devel
  - R_VERSION: oldrel
  - R_VERSION: release
  - R_VERSION: 3.3.0


build_script:
  - cmd: >-

      Rscript -e "install.packages(c('devtools'), repos='https://cran.r-project.org')" --no-init-file

      Rscript -e "devtools::install_deps(pkg = 'packages/RSuite',dep = T)" --no-init-file

      Rscript -e "devtools::document(pkg = 'packages/RSuite')"

      R CMD build .\packages\RSuite

      R CMD check .\*tar.gz --no-manual

test_script:
  - cmd: Rscript -e "devtools::install('./packages/RSuite')"
  - cmd: Rscript -e "source('tests/run_tests.R', chdir = TRUE)"

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

on_finish:
  - 7z a logs.zip tests\logs*
  - appveyor PushArtifact logs.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
