# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

environment:
  USE_RTOOLS: true

  matrix:
  - R_VERSION: devel
  - R_VERSION: oldrel
  - R_VERSION: release

install:
  - ps: Bootstrap

build_script:
  - cmd: >-
      cd packages/RSuite

      Rscript -e "install.packages(c('devtools'), repos='https://cran.r-project.org')" --no-init-file

      Rscript -e "devtools::install_deps(dep = T)" --no-init-file

      Rscript -e "devtools::document()"

      R CMD build .

      R CMD check *tar.gz --no-manual

test_script:
  - cmd: R CMD INSTALL .
  - cmd: R -e "testthat::test_dir('../../tests')"

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
