#----------------------------------------------------------------------------
# RSuite
# Copyright (c) 2017, WLOG Solutions
#
# Utilities related to package documentation building.
#----------------------------------------------------------------------------

#'
#' Builds package documentation if required.
#'
#' @param pkg_name name of package to build documentation for. (type: character)
#' @param pkg_path path to the package. (type: character)
#' @param rver R version to build package with. (type: character)
#' @param libpath library path to use during building. (type: character)
#'
#' @return TRUE if documentation build was not required or built it succesfully.
#'
#' @keywords internal
#'
pkg_build_docs <- function(pkg_name, pkg_path, rver, libpath) {
  # first remove Rd file built with roxygen
  removed <- lapply(X = list.files(file.path(pkg_path, "man"), ".+[.]Rd$", full.names = T),
                    FUN = function(rd_file) {
                      if (!all(grepl("^% Generated by roxygen", readLines(rd_file, n = 1)))) {
                        return(FALSE)
                      }
                      unlink(rd_file, force = T)
                      return(TRUE)
                    })

  ns_path <- file.path(pkg_path, "NAMESPACE")
  build_ns <- !file.exists(ns_path) || any(grepl("^# Generated by roxygen", readLines(ns_path, n = 1)))

  if (!build_ns && length(removed) != 0 && !any(unlist(removed))) {
    # documentation building is not required
    return(TRUE)
  }

  if (build_ns) {
    # put imports into NAMESPACE file as they will be needed to build
    # documentation properly.
    #
    writeLines(c("# Generated by roxygen2: do not edit by hand", # for roxygen to regenerate it
                 "",
                 sprintf("import(%s)", get_package_desc_imports(pkg_path))),
               con = ns_path)
  }

  doc_res <- run_rscript("devtools::document(%s)",
                         rscript_arg("pkg", pkg_path),
                         rver = rver, ex_libpath = libpath)
  if (!is.null(doc_res)) {
    if (doc_res == FALSE) {
      pkg_logwarn("Document building aborted for %s", pkg_name)
    } else {
      pkg_logwarn("Document building for %s failed: %s", pkg_name, doc_res)
    }
    return(FALSE)
  }
  return(TRUE)
}

#'
#' Retrieves all package imports declared in DESCRIPTION file.
#'
#' @param pkg_path path to the package. (type: character)
#'
#' @return character vector with all the package declared imports.
#'
#' @keywords internal
#'
get_package_desc_imports <- function(pkg_path) {
  desc_file <- file.path(pkg_path, "DESCRIPTION")
  stopifnot(file.exists(desc_file))

  desc_imports <- read.dcf(desc_file, fields = "Imports")[1, "Imports"]
  desc_imports <- unlist(strsplit(desc_imports, ","))
  desc_imports <- gsub("^\\s*([a-zA-Z0-9]+).*$", "\\1", desc_imports)
  desc_imports <- desc_imports[!is.na(desc_imports)]
  return(desc_imports)
}

#'
#' Checks if package imports declaration is consistent with namespace.
#' If imports declared but not present in NAMESPACE it gets updated.
#'
#' Logs warning message describing all inconsistencies.
#'
#' @param pkg_name name of package. (type: character)
#' @param pkg_path path to package folder. (type: character)
#'
#' @return TRUE if declarations are consitent, FALSE overvise.
#'
#' @keywords internal
#'
validate_package_imports <- function(pkg_name, pkg_path) {
  desc_imports <- get_package_desc_imports(pkg_path)

  ns_file <- file.path(pkg_path, "NAMESPACE")
  stopifnot(file.exists(ns_file))

  ns_lines <- readLines(ns_file)
  ns_imports <- ns_lines[grepl("^\\s*import[(]\\s*[a-zA-Z0-9]+\\s*[)]\\s*$", ns_lines)]
  ns_imports <- gsub("^\\s*import[()]\\s*([a-zA-Z0-9]+)\\s*[)]\\s*$", "\\1", ns_imports)

  desc_not_ns <- setdiff(desc_imports, ns_imports)
  if (length(desc_not_ns) > 0) {
    pkg_logwarn("Updating NAMESPACE file of %s package to contain %s",
                pkg_name, paste(desc_not_ns, collapse = ", "))
    writeLines(c(ns_lines, sprintf("import(%s)", desc_not_ns)),
               con = ns_file)
  }

  ns_not_desc <- setdiff(ns_imports, desc_imports)
  if (length(ns_not_desc) > 0) {
    pkg_logwarn("Imports present in NAMESPACE are not declared in DESCRIPTION of %s: %s",
                pkg_name, paste(ns_not_desc, collapse = ", "))
    return(FALSE)
  }

  return(TRUE)
}
